### ISSUE TITLE
update main config.json for CEUS model

### ISSUE THREAD

**Issue by ashumway-usgs** [usgs/nshm-cous-2018#17]
Need to update the config.json file (located in usgs/nshm-cous-2018/Central & Eastern US directory). 

1. Model name needs to be updated (2014 updated to 2018).

2. List of IMTs need to be updated (PGA, SA0P2, and SA1P0 to PGA, SA0P01, SA0P02, SA0P03, SA0P05, SA0P075, SA0P1, SA0P15, SA0P2, SA0P25, SA0P3, SA0P4, SA0P5, SA0P75, SA1P0, SA1P5, SA2P0, SA3P0, SA4P0, and SA5P0). This is a modified set of the NGA IMTs.

**Comment by pmpowers-usgs** [comment]
Resolved with PR #19
